name: mopup
description: "A client app for mopup."
publish_to: 'none'
version: 3.0.15+350

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Управление состоянием и навигация
  get: ^4.7.2

  # Локальное хранилище и сеть
  get_storage: ^2.1.1
  dio: ^5.4.3
  http: ^1.2.0
  geolocator: ^14.0.2

  # Интерфейс
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  image_picker: ^1.1.2
  syncfusion_flutter_gauges: ^31.2.10
  syncfusion_flutter_datepicker: ^31.2.10
  timeago: ^3.7.1
  yandex_mapkit: ^4.2.1
  flutter_html: ^3.0.0

  # Локальные уведомления
  flutter_local_notifications: ^19.5.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  # Обработка текста и ввода
  characters: ^1.4.0
  mask_text_input_formatter: ^2.5.0
  easy_refresh: ^3.4.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Качество кода
  flutter_lints: ^6.0.0

  # Генерация ресурсов
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/figma/
    - assets/logo.jpg
    - assets/logo.png

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true
  image: assets/figma/mopup_logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/figma/mopup_logo_android12.png
    icon_background_color: "#FFFFFF"
    
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/logo.png
  web:
    generate: true
    image_path: assets/logo.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: assets/logo.png
  macos:
    generate: true
    image_path: assets/logo.png
  linux:
    generate: true
    image_path: assets/logo.png

